name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1
      with:
        default: false
        version: "1.57.0.2"
        ldproxy: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
